#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Initializing some shell variables with directory names
#


export BASE=$HOME/Documents/prog/rakudo/modules
export THIS_DIR=$PWD
export PATH=$PATH:$THIS_DIR/util
